package medicine.ui;

import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import medicine.dao.CompanyDao;
import medicine.dao.LocationDao;
import medicine.dao.MedicineDao;
import medicine.dao.MedicineStockDao;
import medicine.dao.MedicineTypeDao;
import medicine.dao.StockDao;
import medicine.dao.UnitDao;
import medicine.model.Company;
import medicine.model.Location;
import medicine.model.Medicine;
import medicine.model.MedicineType;
import medicine.model.Stock;
import medicine.model.Unit;
import medicine.model.User;

public final class MedicineForm extends javax.swing.JInternalFrame {

    private Medicine medicine;
    private Stock stock;
    private final User user;
    private MedicineStockDao medicineStockDao;

    public MedicineForm(User user) {
        initComponents();
        this.user = user;
        loadCompanyList();
        loadDozes();
        loadUnits();
        loadLocationList();
        enableButtons();
        clearForm();

        cbMedicine.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() != 38 && e.getKeyCode() != 40 && e.getKeyCode() != 10) {
                    String a = cbMedicine.getEditor().getItem().toString();
                    String formatedString = a.toUpperCase();
                    cbMedicine.removeAllItems();
                    cbMedicine.addItem(null);

                    int st = 0;

                    if (formatedString.length() >= 3) {
                        MedicineDao medicineDao = new MedicineDao();
                        for (Medicine m : medicineDao.getMatch(formatedString)) {
                            cbMedicine.addItem(m);
                            st++;
                        }
                    }

                    cbMedicine.getEditor().setItem(a);
                    cbMedicine.hidePopup();
                    if (st != 0) {
                        cbMedicine.showPopup();
                    }
                }
            }
        });
    }

    public void loadDozes() {
        MedicineTypeDao dozeDao = new MedicineTypeDao();
        cbDoze.removeAllItems();
        for (MedicineType tp : dozeDao.display()) {
            cbDoze.addItem(tp);
        }
    }

    public void loadUnits() {
        UnitDao unitDao = new UnitDao();
        cbUnit.removeAllItems();
        for (Unit u : unitDao.display()) {
            cbUnit.addItem(u);
        }
    }

    public void loadCompanyList() {
        CompanyDao companyDao = new CompanyDao();
        cbCompanyName.removeAllItems();
        for (Company c : companyDao.display()) {
            cbCompanyName.addItem(c);
        }
    }

    public void loadLocationList() {
        LocationDao locationDao = new LocationDao();
        cbLocation.removeAllItems();
        for (Location lo : locationDao.display()) {
            cbLocation.addItem(lo);
        }
    }

    public void enableButtons() {
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    public void disableButtons() {
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }

    public void clearForm() {
        tfMedicineName.setText("");
        tfPurchase.setText("");
        tfReorderLevel.setText("");
        tfSales.setText("");
        cbMedicine.setSelectedItem(null);
        tfStartingStock.setText("");
        cbCompanyName.setSelectedIndex(-1);
        cbDisplay.setSelectedIndex(0);
        cbDoze.setSelectedIndex(-1);
        cbUnit.setSelectedIndex(-1);
        cbLocation.setSelectedIndex(-1);
        chExpiracyDate.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        cbMedicine = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfMedicineName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbCompanyName = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbDoze = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfPurchase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfSales = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfStartingStock = new javax.swing.JTextField();
        tfReorderLevel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chExpiracyDate = new com.toedter.calendar.JDateChooser();
        cbDisplay = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbUnit = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbLocation = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("MEDICINE");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Medicine Name");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cbMedicine.setEditable(true);
        cbMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMedicine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnFind)
                    .addComponent(cbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Medicine Name");

        tfMedicineName.setText("jTextField1");

        jLabel2.setText("Company Name");

        cbCompanyName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Format");

        cbDoze.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Unit Purchase");

        tfPurchase.setText("jTextField2");

        jLabel6.setText("Unit Sales");

        tfSales.setText("jTextField3");

        jLabel7.setText("Statring Stock");

        tfStartingStock.setText("jTextField4");

        tfReorderLevel.setText("jTextField5");

        jLabel9.setText("Expiracy");

        cbDisplay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show", "Hide" }));

        jLabel12.setText("Reorder");

        jLabel13.setText("Display");

        jLabel8.setText("Unit");

        cbUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Location");

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMedicineName)
                    .addComponent(cbCompanyName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbUnit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfStartingStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPurchase, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chExpiracyDate, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfReorderLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(cbDoze, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSales)
                            .addComponent(cbDisplay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(cbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMedicineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbDoze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfStartingStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chExpiracyDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String medicineName = tfMedicineName.getText();
        String unitPurchase = tfPurchase.getText();
        String unitSales = tfSales.getText();
        String startingStock = tfStartingStock.getText();
        String reorderLevel = tfReorderLevel.getText();

        if (medicineName.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Medicine Name ???");
        } else if (unitPurchase.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Unit Purchase ???");
        } else if (unitSales.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Unit Sales ???");
        } else if (startingStock.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Starting Stock ???");
        } else if (reorderLevel.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Reorder Level ???");
        } else if (cbCompanyName.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Select Company ???");
        } else {
            try {
                medicine = new Medicine();
                medicine.setCompany((Company) cbCompanyName.getSelectedItem());
                if (cbDisplay.getSelectedIndex() == 1) {
                    medicine.setDisplay(0);
                } else {
                    medicine.setDisplay(1);
                }
                medicine.setMedicineType((MedicineType) cbDoze.getSelectedItem());
                medicine.setUnit((Unit) cbUnit.getSelectedItem());
                medicine.setLocation((Location) cbLocation.getSelectedItem());
                medicine.setMedicineName(medicineName.trim());
                medicine.setUnitPurchase(Double.parseDouble(unitPurchase));
                medicine.setUnitSales(Double.parseDouble(unitSales));
                medicine.setUser(user);

                stock = new Stock();
                stock.setExpiracyDate(chExpiracyDate.getDate());
                stock.setReorderLevel(Integer.parseInt(reorderLevel));
                stock.setStartingStock(Integer.parseInt(startingStock));
                stock.setStockQuantity(Integer.parseInt(startingStock));
                medicine.setStock(stock);

                medicineStockDao = new MedicineStockDao();
                if (medicineStockDao.savem(medicine) != null) {
                    JOptionPane.showMessageDialog(this, "Record saved successfully.");
                    enableButtons();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Record Cannot Save !!!");
                }

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error..." + e);
                JOptionPane.showMessageDialog(this, "Error...");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed

        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        String medicineName = tfMedicineName.getText();
        String unitPurchase = tfPurchase.getText();
        String unitSales = tfSales.getText();
        String startingStock = tfStartingStock.getText();
        String reorderLevel = tfReorderLevel.getText();

        if (medicineName.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Medicine Name ???");
        } else if (unitPurchase.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Unit Purchase ???");
        } else if (unitSales.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Unit Sales ???");
        } else if (startingStock.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Starting Stock ???");
        } else if (reorderLevel.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert Reorder Level ???");
        } else if (cbCompanyName.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Select Company ???");
        } else if (cbDoze.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Select Doze ???");
        } else {
            try {
                medicine.setCompany((Company) cbCompanyName.getSelectedItem());
                if (cbDisplay.getSelectedIndex() == 1) {
                    medicine.setDisplay(0);
                } else {
                    medicine.setDisplay(1);
                }
                medicine.setMedicineType((MedicineType) cbDoze.getSelectedItem());
                medicine.setUnit((Unit) cbUnit.getSelectedItem());
                medicine.setLocation((Location) cbLocation.getSelectedItem());
                medicine.setMedicineName(medicineName);
                medicine.setUnitPurchase(Double.parseDouble(unitPurchase));
                medicine.setUnitSales(Double.parseDouble(unitSales));
                medicine.setUser(user);

                StockDao stockDao = new StockDao();
                stock = stockDao.find(String.valueOf(medicine.getMedicineId()));

                stock.setExpiracyDate(chExpiracyDate.getDate());
                stock.setReorderLevel(Integer.parseInt(reorderLevel));
                int stockQuantity = (stock.getStockQuantity() - stock.getStartingStock()) + Integer.parseInt(startingStock);
                stock.setStockQuantity(stockQuantity);
                stock.setStartingStock(Integer.parseInt(startingStock));
                medicine.setStock(stock);

                medicineStockDao = new MedicineStockDao();
                medicineStockDao.updatem(medicine);

                clearForm();
                enableButtons();
                JOptionPane.showMessageDialog(this, "Record updated successfully.");

            } catch (HeadlessException | NumberFormatException e) {
                System.out.println("Error..." + e);
                JOptionPane.showMessageDialog(this, "Error...");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int check = JOptionPane.showConfirmDialog(this, "Are you sure ???");
        if (check == 0) {
            MedicineDao dao = new MedicineDao();
            if (dao.delete(medicine)) {
                JOptionPane.showMessageDialog(this, "Deleted Successfully.");
                enableButtons();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Delete !!!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clearForm();
        enableButtons();
    }//GEN-LAST:event_btnClearActionPerformed

    private void cbMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicineActionPerformed

        Medicine m = (Medicine) cbMedicine.getSelectedItem();

        medicineStockDao = new MedicineStockDao();
        medicine = medicineStockDao.findByName(m.getMedicineName());

        try {
            if (medicine.getMedicineId() != 0) {
                tfMedicineName.setText(medicine.getMedicineName());
                tfPurchase.setText("" + medicine.getUnitPurchase());
                cbCompanyName.getModel().setSelectedItem(medicine.getCompany());
                cbDoze.getModel().setSelectedItem(medicine.getMedicineType());
                cbUnit.getModel().setSelectedItem(medicine.getUnit());
                cbLocation.getModel().setSelectedItem(medicine.getLocation());
                tfReorderLevel.setText("" + medicine.getStock().getReorderLevel());
                tfStartingStock.setText("" + medicine.getStock().getStartingStock());
                tfSales.setText("" + medicine.getUnitSales());
                tfStartingStock.setText("" + medicine.getStock().getStartingStock());
                if (medicine.getDisplay() == 1) {
                    cbDisplay.setSelectedIndex(0);
                } else {
                    cbDisplay.setSelectedIndex(1);
                }
                chExpiracyDate.setDate(medicine.getStock().getExpiracyDate());

                disableButtons();
            } else {
                JOptionPane.showMessageDialog(this, "No Such Medicine Found ???");
            }
        } catch (NullPointerException e) {
            System.out.println("Error.." + e);
            JOptionPane.showMessageDialog(this, "No Such Medicine Found ???");
        }
    }//GEN-LAST:event_cbMedicineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbCompanyName;
    private javax.swing.JComboBox cbDisplay;
    private javax.swing.JComboBox cbDoze;
    private javax.swing.JComboBox cbLocation;
    private javax.swing.JComboBox cbMedicine;
    private javax.swing.JComboBox cbUnit;
    private com.toedter.calendar.JDateChooser chExpiracyDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfMedicineName;
    private javax.swing.JTextField tfPurchase;
    private javax.swing.JTextField tfReorderLevel;
    private javax.swing.JTextField tfSales;
    private javax.swing.JTextField tfStartingStock;
    // End of variables declaration//GEN-END:variables
}
