package medicine.ui;

import java.awt.HeadlessException;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import medicine.dao.PurchaseReturnDao;
import medicine.dao.PurchaseReturnDeatilsDao;
import medicine.dao.PurchaseReturnMasterDao;
import medicine.model.Client;
import medicine.model.Medicine;
import medicine.model.PurchaseReturnDetails;
import medicine.model.PurchaseReturnMaster;
import medicine.model.PurchaseReturnTaken;
import medicine.model.User;

public final class PurchaseReturnTakenUI extends javax.swing.JInternalFrame {

    private final User user;
    private PurchaseReturnMaster master;
    private PurchaseReturnDao returnDao;
    private PurchaseReturnMasterDao masterDao;
    private PurchaseReturnDeatilsDao detailsDao;
    private LinkedList<Medicine> tempList;
    private HashMap<Integer, PurchaseReturnDetails> tempDetails;
    private PurchaseReturnTaken purchaseReturnTaken;

    public PurchaseReturnTakenUI(User user) {
        initComponents();
        this.user = user;
        loadRep();
        clearForm();        
        itemTable.setShowGrid(true);
    }

    public void loadRep() {
        masterDao = new PurchaseReturnMasterDao();
        cbRepresentative.removeAllItems();
        for (Map.Entry<Long, Client> en : masterDao.getRepresentativeList().entrySet()) {
            //long object = en.getKey();//Client client = en.getValue();
            cbRepresentative.addItem(en.getValue());
        }
    }

    public void enableButtons() {
        btnSave.setEnabled(true);
        btnDelete.setEnabled(false);
    }

    public void disableButtons() {
        btnSave.setEnabled(false);
        btnDelete.setEnabled(true);
    }

    public void clearForm() {
        tempList = new LinkedList<>();
        tempDetails = new HashMap<>();

        tfSubmit.setText("");
        tfToSubmit.setText("");
        cbMedicine.setSelectedIndex(-1);
        cbRepresentative.setSelectedIndex(-1);
        cbReturnNo.setSelectedIndex(-1);
        chSubmitDate.setDate(new Date());

        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbRepresentative = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbReturnNo = new javax.swing.JComboBox();
        btnFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbMedicine = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tfToSubmit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSubmit = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        chSubmitDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("PURCHASE RETURN TAKEN");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("REPRESENTATIVE");

        cbRepresentative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRepresentativeActionPerformed(evt);
            }
        });

        jLabel2.setText("RETURN NO");

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRepresentative, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbReturnNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRepresentative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbReturnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Submit Quantity"
            }
        ));
        itemTable.setRowHeight(22);
        itemTable.setRowMargin(2);
        jScrollPane1.setViewportView(itemTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Medicine");

        cbMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedicineActionPerformed(evt);
            }
        });

        jLabel4.setText("To Submit");

        tfToSubmit.setEditable(false);
        tfToSubmit.setText("jTextField1");

        jLabel5.setText("Submit");

        tfSubmit.setText("jTextField2");
        tfSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubmitActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicine/icon/math-add-icon-16px.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicine/icon/math-minus-icon-16px.png"))); // NOI18N

        jLabel6.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMedicine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chSubmitDate, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(tfToSubmit))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSubmit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfToSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chSubmitDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clearForm();

    }//GEN-LAST:event_btnClearActionPerformed

    private void cbRepresentativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRepresentativeActionPerformed

        try {
            if (cbRepresentative.getSelectedItem() != null) {
                Client c = (Client) cbRepresentative.getSelectedItem();
                masterDao = new PurchaseReturnMasterDao();
                cbReturnNo.removeAllItems();
                for (PurchaseReturnMaster mas : masterDao.getSingleRepReturn(c)) {
                    cbReturnNo.addItem(mas);
                }
                cbReturnNo.setSelectedIndex(-1);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbRepresentativeActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed

        tempDetails = new HashMap<>();

        master = (PurchaseReturnMaster) cbReturnNo.getSelectedItem();
        detailsDao = new PurchaseReturnDeatilsDao();
        cbMedicine.removeAllItems();
        for (PurchaseReturnDetails det : detailsDao.childUnderParent(master)) {
            if (det.getReturnQuantity() != det.getSubmitQuantity()) {
                cbMedicine.addItem(det);
                tempDetails.put(det.getMedicine().getMedicineId(), det);
            }
        }

        if (tempDetails.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All Returns are Taken.");
        }

        cbMedicine.setSelectedItem(null);
        tfSubmit.setText("");
        tfToSubmit.setText("");

    }//GEN-LAST:event_btnFindActionPerformed

    private void cbMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedicineActionPerformed

        try {
            PurchaseReturnDetails det = (PurchaseReturnDetails) cbMedicine.getSelectedItem();
            tfToSubmit.setText("" + (det.getReturnQuantity() - det.getSubmitQuantity()));

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbMedicineActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        PurchaseReturnDetails det = (PurchaseReturnDetails) cbMedicine.getSelectedItem();
        String submitQty = tfSubmit.getText();

        if (submitQty.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Insert submit Quantity ???");
        } else if (det.getReturnQuantity() < Integer.parseInt(submitQty)) {
            JOptionPane.showMessageDialog(this, "Verify Submit Quantity !!!");
            tfSubmit.requestFocus();
        } else {
            if (!tempList.contains(det.getMedicine())) {
                model.addRow(new Object[]{det.getMedicine(), Integer.parseInt(submitQty)});
                tempList.add(det.getMedicine());
                det.setSubmitQuantity(det.getSubmitQuantity() + Integer.parseInt(submitQty));
                tempDetails.put(det.getMedicine().getMedicineId(), det);
            } else {
                JOptionPane.showMessageDialog(this, "Medicine Exists !!!");
            }
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        int itemsTaken = model.getRowCount();

        if (itemsTaken <= 0) {
            JOptionPane.showMessageDialog(this, "No Medicine Selected ???");
        } else {
            try {
                for (int i = 0; i < itemsTaken; i++) {
                    purchaseReturnTaken = new PurchaseReturnTaken();
                    Medicine medicine = (Medicine) model.getValueAt(i, 0);
                    int quantity = (int) model.getValueAt(i, 1);
                    PurchaseReturnDetails det = (PurchaseReturnDetails) tempDetails.get(medicine.getMedicineId());
                    purchaseReturnTaken.setReturnDetails(det);
                    purchaseReturnTaken.setQuantity(quantity);
                    purchaseReturnTaken.setUser(user);
                    purchaseReturnTaken.setTakenDate(chSubmitDate.getDate());
                    returnDao = new PurchaseReturnDao();
                    returnDao.returnTaken(purchaseReturnTaken, det);

                }
                model.setRowCount(0);
                cbReturnNo.removeAllItems();
                cbMedicine.removeAllItems();
                tfSubmit.setText("");
                tfToSubmit.setText("");

                JOptionPane.showMessageDialog(this, "Record saved successfully.");
            } catch (HeadlessException e) {
                System.out.println("Error..." + e);
            }
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubmitActionPerformed

        btnAdd.doClick();
    }//GEN-LAST:event_tfSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int check = JOptionPane.showConfirmDialog(this, "Are you sure ???");
        if (check == 0) {
            returnDao = new PurchaseReturnDao();
            returnDao.returnDelete(master);
            
            clearForm();
            JOptionPane.showMessageDialog(this, "Return Deleted Successfully.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbMedicine;
    private javax.swing.JComboBox cbRepresentative;
    private javax.swing.JComboBox cbReturnNo;
    private com.toedter.calendar.JDateChooser chSubmitDate;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfSubmit;
    private javax.swing.JTextField tfToSubmit;
    // End of variables declaration//GEN-END:variables
}
